name: Local Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Self Test
        uses: ./
        with:
          path: "test/data/valid"