name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Self Test
        uses: PurdueECE/action-pylint@main
        with:
          path: "test/data/valid"